version: '2'

# Go task : https://taskfile.org

tasks:
  validate:
    desc: Validate Cloudformation syntax
    cmds:
      - sam validate --template {{.TEMPLATE}}

  package:
    desc: transform and package cloudfomartion template to Amazon S3
    deps: []
    cmds:
      - sam package --s3-bucket {{.S3_BUCKET}} --template {{.TEMPLATE}} --output-template-file packaged.yaml

  deploy:
    desc: Deploy cloudformation template
    deps: [package,validate]
    cmds:
      - sam deploy --s3-bucket {{.S3_BUCKET}} --template-file packaged.yaml --capabilities CAPABILITY_IAM --stack-name {{.STACK_NAME}}

  delete:
    desc: Delete cloudformation stack
    cmds:
      - aws cloudformation delete-stack --stack-name {{.STACK_NAME}}
    